Fix: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory pass in class
It occurs when java runtime system doesn’t find a class definition, which is present at compile time, but missing at run time.